### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by Meta-YZ** [Derekabc/MARL_CAVs#1]
Hi! Your article is  great of original! Thank you very much for opening up the other algorithms! Will your algorithm be open source?(Deep Multi-agent Reinforcement Learning for Highway On-Ramp Merging in Mixed Traffic)

**Comment by DongChen06** [comment]
Hi YuanZhuo, thanks for your interest! We may make them open-sourced after acceptance. While if you are interested in the Safety supervisor part, it is already in the [code](https://github.com/Derekabc/MARL_CAVs/blob/main/highway-env/highway_env/envs/common/abstract.py).

**Comment by Meta-YZ** [comment]
Thanks! Really looking forward to
