### ISSUE TITLE
what if Episode before train is set more than 1

### ISSUE THREAD

**Issue by wangshuo1994** [Derekabc/MARL_CAVs#10]
Thank you for your clear code! Could you help me figure out the error: When episode before train is set more than 1, the following line  "states_var = to_tensor_var(batch.states, self.use_cuda).view(-1, self.n_agents, self.state_dim)" in MAPPO  will raise ValueError: setting an array element with a sequence. Thank you in advance!

**Comment by DongChen06** [comment]
Hi @wangshuo1994, thanks for your interest! We update the network in an online way: after each episode, if you want to train the model (e.g., PPO, A2C) in an offline way (i.e., using a reply buffer to store old experience), you may need to edit the training function. Thanks.

**Comment by wangshuo1994** [comment]
@Derekabc Thank you for your help!
