### ISSUE TITLE
something wrong with the reset() function

### ISSUE THREAD

**Issue by PeiyanFlying** [Derekabc/MARL_CAVs#11]
I got this error when I tried to run either run_xxx.py or mpc_main.py. It looks like somewhere in the observation is a little bit glitchy. Would you mind helping me to look at it? It seems that there are some values which are out of the range  [-1,1] or the dimension is not right. Thank you!

![Screenshot from 2022-07-01 20-09-15](https://user-images.githubusercontent.com/45463777/176984573-a17f93a7-eced-4978-8271-8fee70259bc4.png)
![Screenshot from 2022-07-01 20-00-26](https://user-images.githubusercontent.com/45463777/176984424-af1e1d91-5504-4b27-a80a-938e96193a89.png)

**Comment by DongChen06** [comment]
could you provide more details, since I haven't come across this issue before?

**Comment by PeiyanFlying** [comment]
![Screenshot from 2022-07-01 20-27-17](https://user-images.githubusercontent.com/45463777/176985010-24e9e24e-6171-4d2d-b50b-55b26bf2a05d.png)
(should be the thing start with the array, the line above is the args = parse_args())
This is what I got for the observation and the observation space is an spaces.Box object and it looks like it's in the highway_env/envs/common 
class KinematicObservation
    def space(self) -> spaces.Space:
        return spaces.Box(shape=(self.vehicles_count, len(self.features)), low=-1, high=1, dtype=np.float32)

**Comment by PeiyanFlying** [comment]
It seems like this error is saying that the result of the env.reset() is not in the env.observation_space, which is a KinematicObservation, with spaces.Box(shape=(self.vehicles_count, len(self.features)), low=-1, high=1, dtype=np.float32) as the characteristic, and looks like self.vehicles_count = 5, len(self.features) = 5.

**Comment by DongChen06** [comment]
A quick try: try to use gym==0.15.4

**Comment by PeiyanFlying** [comment]
![Screenshot from 2022-07-01 21-43-58](https://user-images.githubusercontent.com/45463777/176986839-0715809e-b424-4ccc-8645-0b79770347f3.png)
![Screenshot from 2022-07-01 21-39-07](https://user-images.githubusercontent.com/45463777/176986734-9c9fb777-60d5-4159-a359-7b23d583e7fe.png)


This issue was solved, but I get another error...

**Comment by DongChen06** [comment]
have you changed any settings?

**Comment by PeiyanFlying** [comment]
I don't think so. But it works for mpc_main.py! Yet tried to re-download the directory with run_xxx.py and they still give me this issue.

**Comment by DongChen06** [comment]
@PeiyanFlying Have you addressed the issue. I tested the repo again and did not find any issues with the default requirements. If you still face the issue, you may send me an email and then we can address it together.

**Comment by PeiyanFlying** [comment]
Sorry for the late reply! it worked after I updated my pytorch to the corresponding version of my nvidia setting. Thank you very much!
