### ISSUE TITLE
Implementing MAPPO for continuous action space

### ISSUE THREAD

**Issue by Lplenka** [Derekabc/MARL_CAVs#13]
Hello @Derekabc, if you have some time, I was hoping you could help me convert the [MAPPO.py](https://github.com/Derekabc/MARL_CAVs/blob/main/MARL/MAPPO.py) code to work for continuous action in [action.py](https://github.com/Derekabc/MARL_CAVs/blob/main/highway-env/highway_env/envs/common/action.py#L60).

I tried updating the action code from this

```
def exploration_action(self, state, n_agents):
    softmax_actions = self._softmax_action(state, n_agents)
    actions = []
    for pi in softmax_actions:
        actions.append(np.random.choice(np.arange(len(pi)), p=pi))
    return actions
```
to this

```
def exploration_action(self, state, n_agents):
    softmax_actions = self._softmax_action(state, n_agents)
    return softmax_actions 
```

But the agent is not learning properly. Maybe I will have to also update the model code in [Model_common.py](https://github.com/Derekabc/MARL_CAVs/blob/main/MARL/single_agent/Model_common.py#L5). I have spent quite a lot of time in experimenting. 

It would be great if you share some ideas on converting the [MAPPO.py] https://github.com/Derekabc/MARL_CAVs/blob/main/MARL/MAPPO.py) code for continuous action. I can share a pull request if I successfully complete it.

Looking forward to your help. Please let me know if you want to connect via email.

P.S. I am big time Naruto fan too 😆 

Looking forward to your suggestions, sensei!

**Comment by DongChen06** [comment]
Hi @Lplenka , it is possible to convert the current models to the continuous action space via changing the current categorical distribution to diagonal Gaussian distribution as suggested at  https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#stochastic-policies

**Comment by Lplenka** [comment]
Thanks @Derekabc, for the tip. I will try to convert the code to work for continuous action.
