### ISSUE TITLE
Checkpoint loaded model

### ISSUE THREAD

**Issue by hongzhangMu** [Derekabc/MARL_CAVs#14]
ERROR:root:Can not find checkpoint for ./results/Sep_21_22_41_51/models/
hi, i have a problem that run_xxx.py,this has some error .How can I get the checkpoint model?

**Comment by DongChen06** [comment]
It is normal and you will get evaluation results soon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: hongzhangmu ***@***.***>
Sent: Wednesday, September 21, 2022 6:52:45 PM
To: DongChen06/MARL_CAVs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DongChen06/MARL_CAVs] Checkpoint loaded model (Issue #14)


ERROR:root:Can not find checkpoint for ./results/Sep_21_22_41_51/models/
hi, i have a problem that run_xxx.py,this has some error .How can I get the checkpoint model?
