### ISSUE TITLE
root:Can not find checkpoint for ./results/Oct_25_02_57_41/models/

### ISSUE THREAD

**Issue by Creak77** [Derekabc/MARL_CAVs#16]
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame.from_records(

I got a future warning about the pandas, can I ask you how to solve this question?

UserWarning: volatile was removed (Variable.volatile is always False)
  if input[0].volatile == False and self.steps % self.Ts == 0:

Also I got this userwarning, how to solve with that?

**Comment by DongChen06** [comment]
Hi, I think it is just a warning, the training is going. You may wait for a while and get results soon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Creak77 ***@***.***>
Sent: Monday, October 24, 2022 11:02:40 PM
To: DongChen06/MARL_CAVs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DongChen06/MARL_CAVs] root:Can not find checkpoint for ./results/Oct_25_02_57_41/models/ (Issue #16)


ERROR:root:Can not find checkpoint for ./results/Oct_25_02_57_41/models/
/home/sdcnlab/Mingfeng/MARL/MARL_CAVs-main/MARL/single_agent/kfac.py:144: UserWarning: volatile was removed (Variable.volatile is always False)
if input[0].volatile == False and self.steps % self.Ts == 0:
/home/sdcnlab/anaconda3/envs/marl_cav/lib/python3.10/site-packages/torch/nn/modules/module.py:1053: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/home/sdcnlab/Mingfeng/MARL/MARL_CAVs-main/MARL/single_agent/Model_common.py:62: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
act = self.actor_output_act(self.actor_linear(out))
/home/sdcnlab/Mingfeng/MARL/MARL_CAVs-main/MARL/single_agent/kfac.py:144: UserWarning: volatile was removed (Variable.volatile is always False)

I got this error after I install a old version of pandas, can I ask you how to solve this problem?

**Comment by Creak77** [comment]
oh thank you, both of them are only warning, I can just ignore it right?

**Comment by DongChen06** [comment]
Yes, the code will output results every 200 episodes, so you may get the results soon if you have a dedicated device

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Creak77** [comment]
thanks！I will try it and if I have more questions I will ask you about that

Dong Chen ***@***.***>于2022年10月24日 周一下午11:55写道：
