### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by zzh-i** [Derekabc/MARL_CAVs#17]
Hi! Your article is great of original and thanks for your code.Do you train on the GPU server? I train very slowly on the Windows computer. Is there any way to speed up the training? Thanks.

**Comment by DongChen06** [comment]
Hi, thank you for reaching out! actually, there are no big differences between training with or without GPUs in my experience. However, generally speaking, a dedicated desktop would be faster than a laptop.

**Comment by zzh-i** [comment]
Thanks!
