### ISSUE TITLE
Libraries I was used

### ISSUE THREAD

**Issue by DongChen06** [Derekabc/MARL_CAVs#18]
![image](https://user-images.githubusercontent.com/25771207/221904440-a4029fb8-cc6c-4b3a-bb8c-7b9fba1956b1.png)

![image](https://user-images.githubusercontent.com/25771207/221904506-94cf4109-7206-4cb9-bfed-da4e9a2eefec.png)

![image](https://user-images.githubusercontent.com/25771207/221904554-f86f8a4c-74fe-42ef-8a8b-ae76bd38e069.png)

![image](https://user-images.githubusercontent.com/25771207/221904617-bb9ba12c-302f-48dd-846f-8ea6184298db.png)

**Comment by huang6668** [comment]
Hello, may I ask what version of Highway-env you are using?

**Comment by DongChen06** [comment]
Hi @huang6668 , to run the code, you do not install the current highway version.

**Comment by huang6668** [comment]
Okay, thank you. I'm currently exploring how to convert the scene to intersection and I've encountered some issues. However, the code runs successfully in your scence.
