### ISSUE TITLE
Taking the liberty of asking you a question

### ISSUE THREAD

**Issue by Jonyian** [Derekabc/MARL_CAVs#22]
Hello, may I ask when you can open the source of the new method you mentioned in the paper? Very interested in this. thank you very much

**Comment by DongChen06** [comment]
Hello, thanks for your interest. It is already to open the codes, however, I do not have time to clean up the codes recently. If you want, you could send me an email and I will send you a copy. Thanks!

**Comment by Jonyian** [comment]
Hello, thank you very much. I have sent you an email. Thank you again

**Comment by DongChen06** [comment]
I did not receive any emails for codes, please check the email address. Thank you!

**Comment by HuXingYu1016** [comment]
Hello, I also sent an email to you because the interest to your exciting work. Thank you!
