### ISSUE TITLE
can l ask you a question

### ISSUE THREAD

**Issue by wolf212121j** [Derekabc/MARL_CAVs#23]
你好，我对您的工作很感兴趣，我在将gym版本降低到0.21.0后，我发现我运行run_madqn.py 这个文件的时候没有反应，您好，请问这是为什么啊
![选区_046](https://github.com/DongChen06/MARL_CAVs/assets/127321726/8681ef99-a46e-416a-bf91-7c5293f4f691)

**Comment by DongChen06** [comment]
Hi, thanks for your interest! Could you give more information about your settings? It is hard to tell why it happens with limited information.

**Comment by wolf212121j** [comment]
I successfully ran the first 600 episodes when I ran the mappo.py
![选区_047](https://github.com/DongChen06/MARL_CAVs/assets/127321726/621a8fb5-d182-4c86-8ccf-7557d7bb5e2c)
, but then I encountered such an error, could you please help me to see what the problem is

**Comment by DongChen06** [comment]
it seems it's an issue with your FFMPEG lib, you could try:
```
pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python
```

**Comment by wolf212121j** [comment]
ok，thank you
