### ISSUE TITLE
What should I do after my training is done

### ISSUE THREAD

**Issue by wolf2127** [Derekabc/MARL_CAVs#24]
hello，can l ask you what should I do after my training is done？After my training was done, I got a line chart, a bunch of weights, and a number of training videos.

**Comment by DongChen06** [comment]
You can evaluate the models by changing "train" to "evaluate" in the arguments.

**Comment by wolf2127** [comment]
Thanks a lot! However, when l try to run  a2c.py, l can't find it out such as run_ppo.py     ,   can you give it to me, thank you.

**Comment by zcysun** [comment]
![image](https://github.com/DongChen06/MARL_CAVs/assets/116549148/cdd769d1-502b-4c91-8ce8-3ec72e98a767)
Hello! Is the sentence you mentioned ”You can evaluate the models by changing "train" to "evaluate" in the arguments.“ edited from here?

**Comment by DongChen06** [comment]
Hi @zcysun , First, you need to change the --option from train to evaluate, then please specify the model-dir where you saved the trained models.
![image](https://github.com/DongChen06/MARL_CAVs/assets/25771207/7c857a3e-de7c-4cb6-9e56-ba7cebba39b6)
