### ISSUE TITLE
After training，I have got nothing but models.

### ISSUE THREAD

**Issue by zcysun** [Derekabc/MARL_CAVs#26]
Hello! I have the following questions, and I would greatly appreciate your answers:

1. The program is running very slowly. My workstation is equipped with an RTX 4080 graphics card, and I have confirmed that CUDA and CUDNN are installed correctly (including version compatibility). During runtime, I've noticed that the GPU utilization is actually quite low. The main issue is that after the program finishes running (regardless of which `run_xxx.py`), the terminal doesn't display any errors and remains stuck in the running interface. It continues to show the same status indefinitely, and even after running it overnight, it remains in this state.
![2](https://github.com/DongChen06/MARL_CAVs/assets/116549148/311044f6-e1f9-431d-8248-9007d711139b)

2. Under the conditions described in question 1, I can't determine whether the program has actually finished. However, in the "Results" folder, I find the models as shown in the attached image. Inside this folder, there is only the "models" directory, while the other folders are empty. I haven't obtained training curves, training videos, or similar outputs as others have. I'm wondering where the issue might be.
![Snipaste_2023-09-09_13-15-24](https://github.com/DongChen06/MARL_CAVs/assets/116549148/c32e082a-09db-4842-ba02-acba4e32ccb9)

**Comment by DongChen06** [comment]
Hi @zcysun, Thanks for reaching out! To speed up, you may disable your GPU, you may run faster with CPU only. To know the process of training, there should be some saved logs such as rewards, and speed, you may use them to visualize the training. Also, the models are saved every 200 episodes, you may also be able to see the training process. Normally, the easy mode takes me about 5-6 hours.

**Comment by zcysun** [comment]
Thank you for your response!

Are all three modes (Easy, Medium, Hard) of the program's code better suited for running on the CPU? 
 
Additionally, can I use TensorBoard to visualize the entire running process, such as online recording of average rewards and generating line graphs simultaneously? 
 
Finally, after running the DQN algorithm for 400 episodes (it was also trained for 1000 episodes with the same curve, but I forgot to record), the graph of average rewards looks as shown below. Can you help me identify where the issue might be?
![微信图片_20230909164951](https://github.com/DongChen06/MARL_CAVs/assets/116549148/97385078-6007-43a2-addb-c522312e323d)

Looking forward to your response!

**Comment by DongChen06** [comment]
In my experience, DQN does not work well for this task, Maybe you can try PPO or A2C first
