### ISSUE TITLE
How do I get information about the speed of the vehicles around me?

### ISSUE THREAD

**Issue by zcysun** [Derekabc/MARL_CAVs#31]
Hi:
As shown in the question, I want to get the observation information of the surrounding vehicles (or all the vehicles in the area). For example, I want to calculate the combined cost of all the vehicles in the area, view the speed information of all the vehicles (including self vehicles and HVs), etc., how do I get this information first?

Thank you very much for your answer.

**Comment by zcysun** [comment]
Hello, I have another question. The current average reward graph is drawing a point every 200eposide, how can I modify the frequency to require him to update it every specific eposides, so that the points sampled by the graph can be controlled?

**Comment by DongChen06** [comment]
> Hi: As shown in the question, I want to get the observation information of the surrounding vehicles (or all the vehicles in the area). For example, I want to calculate the combined cost of all the vehicles in the area, view the speed information of all the vehicles (including self vehicles and HVs), etc., how do I get this information first?
> 
> Thank you very much for your answer.

Hi, if you know how to debug, then you may look at the merge_env_v1.py, there should be some variables called road.vehicles. It contains all the vehicle information

**Comment by DongChen06** [comment]
> Hello, I have another question. The current average reward graph is drawing a point every 200eposide, how can I modify the frequency to require him to update it every specific eposides, so that the points sampled by the graph can be controlled?

For this question, you may look at the training codes and modify the log frequency. thanks

**Comment by zcysun** [comment]
谢谢你的回答！我还有另外一个问题，我想关闭渲染功能只想关心代码是否调试通顺，我似乎没有在env/run/maacktr中的一个文件中找到有关render的设置，你能告诉我应该在哪里设置吗？

**Comment by zcysun** [comment]
Thank you very much for your answer! 

Currently the code outputs an average reward graph not with one coordinate point per eposide, but with one reward value per "EVAL_INTERVAL", and it renders and outputs three training videos per EVAL_INTERVAL; this way, when I turn down EVAL_INTERVAL (for debugging purposes) I will be able to save the training videos frequently. I don't actually want the training videos right now, so I have the following questions: 
1. Where can I change the code so that each eposide outputs a reward value so that I end up with a densely-populated average reward plot? 
2. how do I turn off rendering and not have the training video appear and save, I only care about the average reward results.

Also, besides the average reward plot, what other meaningful result plots can I output for analysis?

Thank you very much for your answer!

**Comment by zcysun** [comment]
I'm really sorry for the interruption, but I'd like to ask you a few more questions! 

Looking at the information in road.vehicles as you said, I printed them and the output is as follows:
 ! [output](https://github.com/DongChen06/MARL_CAVs/assets/116549148/95209b81-72d5-4dd3-90b0-db979e048b1f) 
It seems that each vehicle will have three pieces of information, the first being the number (again, a question. Why is this number all three digits when the training video is something like #1#2?) The remaining two numbers I can't seem to find out exactly what they mean, can you tell me? 

Thank you very much for your answer!

**Comment by zcysun** [comment]
I'm very sorry for the inconvenience.
! [Screenshot 2023-11-29 09-43-10](https://github.com/DongChen06/MARL_CAVs/assets/116549148/05e8085f-3d0b-4a83-91c9-a9eb861fa75f)! 
As you can see above, I noticed that the eval_logs and eval_videos folders are empty after each training session. Is this normal? Also, are the training logs saved and where should I look for them?

I would appreciate if you could answer!

**Comment by DongChen06** [comment]
> I'm very sorry for the inconvenience. ! [Screenshot 2023-11-29 09-43-10](https://github.com/DongChen06/MARL_CAVs/assets/116549148/05e8085f-3d0b-4a83-91c9-a9eb861fa75f)! As you can see above, I noticed that the eval_logs and eval_videos folders are empty after each training session. Is this normal? Also, are the training logs saved and where should I look for them?
> 
> I would appreciate if you could answer!

Yes, it is normal. When you implemented the evaluation, there will be videos in the folders

**Comment by zcysun** [comment]
Hello!

After debugging your publicly available code and running MAACKTR algorithm for approximately 1000 episodes, here is the result graph of average rewards. It seems there is no clear convergence trend（I ran it for several more times, but there still seems to be no convergence trend.）. I would like to ask how many episodes it typically takes to achieve convergence, and if it doesn't converge, what are the key parameters to adjust?
![Figure_5](https://github.com/DongChen06/MARL_CAVs/assets/116549148/bc8c5c7b-807a-40fa-aefb-f9d8d6cea7b5)

Thank you for your response!

**Comment by DongChen06** [comment]
> Hello!
> 
> After debugging your publicly available code and running MAACKTR algorithm for approximately 1000 episodes, here is the result graph of average rewards. It seems there is no clear convergence trend（I ran it for several more times, but there still seems to be no convergence trend.）. I would like to ask how many episodes it typically takes to achieve convergence, and if it doesn't converge, what are the key parameters to adjust? ![Figure_5](https://private-user-images.githubusercontent.com/116549148/286814258-bc8c5c7b-807a-40fa-aefb-f9d8d6cea7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTY1MzYsIm5iZiI6MTcwMTM1NjIzNiwicGF0aCI6Ii8xMTY1NDkxNDgvMjg2ODE0MjU4LWJjOGM1YzdiLTgwN2EtNDBmYS1hZWZiLWY5ZDhkNmNlYTdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxNDU3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWY4NDZhNGZjMzIzZDE3ZjcxYzI1YzQwODRhOTQxZjcyNzhlZjYxMDM1ODZhMDI0NGZlN2M3YjFhOGVlNGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gqILTCPxlndCrD3JXnOs-5yAv8mgljXyI6wyBxIh-Ag)
> 
> Thank you for your response!

Hi, which traffic modes you used? You may need 5000-10000 episodes to see an apparent increasing trend.

**Comment by zcysun** [comment]
Thanks for your reply!

The traffic modes is medium, when I increase the number of training rounds to around 10,000 the running time is around 12hours, is this within reason?

Also, I would like to output the same type of average speed graph as in your paper, where do I modify the code?
![截图 2023-12-01 09-23-36](https://github.com/DongChen06/MARL_CAVs/assets/116549148/af2ea617-13df-4156-9ad8-473f21696f89)


Thank you!

**Comment by DongChen06** [comment]
The plot is based on three random seeds. So you may need to run the codes for three times with different seeds.
