### ISSUE TITLE
About baseline in the paper?

### ISSUE THREAD

**Issue by gyccccccccc** [Derekabc/MARL_CAVs#34]
Hi, thank you for your great job first! Could you please tell me how can I change the algorithm“ours” to the normal MAPPO?
I've read the issues posted before, but I can't find this config( namely safety guarantee ＆n_step) in ppo? hope your answer!

**Comment by DongChen06** [comment]
Hi @gyccccccccc , thanks for your question. You may go to this codes and set the safety_supervisor as True: https://drive.google.com/drive/folders/1CPOOYSQzqc0_XUr8durNWDUBv66PUHaM

**Comment by gyccccccccc** [comment]
Thank  you for your kindly help! 
Maybe I didn't make my problem clear, now I want to use MAPPO with no action masking and safety_supervisor , may I just use the code run_MAPPO in the github?

**Comment by DongChen06** [comment]
yes, MAPPO has no safety supervisor and action masking

**Comment by gyccccccccc** [comment]
> yes, MAPPO has no safety supervisor and action masking

Thank you very much!!!
