### ISSUE TITLE
MASAC algorithm

### ISSUE THREAD

**Issue by jsntjyz** [Derekabc/MARL_CAVs#37]
Hello,your work is great. I would like to ask if the MASAC algorithm will be open sourced in the future?

**Comment by DongChen06** [comment]
Hello, we do not plan to open-source the MASAC algorithm. For your reference, you may look at: 

1. Liu, Qianqian, Fengying Dang, Xiaofan Wang, and Xiaoqiang Ren. "Autonomous highway merging in mixed traffic using reinforcement learning and motion predictive safety controller." In 2022 IEEE 25th International Conference on Intelligent Transportation Systems (ITSC), pp. 1063-1069. IEEE, 2022.
2. https://github.com/toshikwa/sac-discrete.pytorch
