### ISSUE TITLE
about SubprocVecEnv

### ISSUE THREAD

**Issue by gyccccccccc** [Derekabc/MARL_CAVs#39]
Hello! Thank you for your great job first!
I'm sorry to bother you, but I find it quite slow when training. So I want to use SubproVecEnv to build multiple envs and train at the same time. However, the SubprocVecEnv seem can't be used in mappo. 
Is there any way to faster the algorithm?

**Comment by DongChen06** [comment]
Hello, thanks for your interest. One way is to just use CPU instead of GPU for the training.

**Comment by gyccccccccc** [comment]
> Hello, thanks for your interest. One way is to just use CPU instead of GPU for the training.

Yes，I've used CPU to train, but it seem that the MAPPO algorithm can not support multi-env(SubprocVecEnv)?
