### ISSUE TITLE
no existing models

### ISSUE THREAD

**Issue by fuleilei17** [Derekabc/MARL_CAVs#4]
Hi! In the closed issue, I see that
"If you can see the output as follows, you are able to run the code. The error means there are no existing models."
![image](https://user-images.githubusercontent.com/62596683/128626155-ac44f60f-f222-4562-96d8-f89b66051ac7.png)
Now I have the same outputs, but I want to know what I should do next to solve "no existing models", I am a rookie in MARL and i am confused. Thanks!!!

**Comment by DongChen06** [comment]
Hi， @fuleilei17, thanks for your interest. Could you please provide more information for your implementation, thus I can help figure out why you come across this issue?

**Comment by fuleilei17** [comment]
Thank you for your reply! I run your code and get output as follows, suggesting that there is no model, 
![image](https://user-images.githubusercontent.com/62596683/128677577-1e78c504-10ae-48f0-af45-0b09d02f1893.png)

I am not sure if this is my problem or? In order to reproduce the work in your paper, what should I do next?

**Comment by DongChen06** [comment]
Hi, I think it should be an error. If possible could you please try it on a ubuntu computer?

**Comment by fuleilei17** [comment]
Hi, I solve the problem which i have mentioned above "TypeError: object of type 'numpy.int32' has no len()", by changing 
File "MARL\common\utils.py" line 37, in index_to_one_hot :
"
one_hot = np.zeros((len(index), dim))
  one_hot[np.arange(len(index)), index] = 1.
"
to 
"
        ss = str(index)
        one_hot = np.zeros((len(ss), dim))
        one_hot[np.arange(len(ss)), index] = 1.
"
because it seems that only str(index) can use len() correctly, not index which is "numpy.int32" type.

**Comment by fuleilei17** [comment]
Hi, now I run the code "run_mappo.py", I can get the result as follow:
![image](https://user-images.githubusercontent.com/62596683/131105394-3bac58b6-5bab-4a91-bad7-834377cd1240.png)

and I can see the videos in the folder, it seems that i run your code successfully, right?
![image](https://user-images.githubusercontent.com/62596683/131105532-9b4bae1c-32db-409d-9b58-6296db00f661.png)

Thank you for sharing such a good project! I am now studying your paper. It seems that you are also a Chinese, I hope your studies go well！

**Comment by DongChen06** [comment]
@fuleilei17, yes, you have the correct output, and also thanks for your kind words.

**Comment by caixxuan** [comment]
> Hi, now I run the code "run_mappo.py", I can get the result as follow: ![image](https://user-images.githubusercontent.com/62596683/131105394-3bac58b6-5bab-4a91-bad7-834377cd1240.png)
> 
> and I can see the videos in the folder, it seems that i run your code successfully, right? ![image](https://user-images.githubusercontent.com/62596683/131105532-9b4bae1c-32db-409d-9b58-6296db00f661.png)
> 
> Thank you for sharing such a good project! I am now studying your paper. It seems that you are also a Chinese, I hope your studies go well！

Did you run in Windows? Did you meet this problem? looking for  help
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/53e17b92-e9d7-4b43-99d3-d6e5590c98fa)

**Comment by onkarrai06** [comment]
Also, is there any way I can run this on my GPU instead? The training seems extremely slow on my CPU which is Ryzen 7 6800H.

@DongChen06
