### ISSUE TITLE
Error: The ‘eval_rewards.npy’ file could not be found while drawing comparison curves

### ISSUE THREAD

**Issue by Idealist-T** [Derekabc/MARL_CAVs#40]
Hello, I found that the 'eval_rewards.npy' file was not generated in the 'results' folder when I drew the comparison curve using the 'plot_benchmark_saft. py' program. The error is as follows. How can I draw the comparison curve correctly? Look forward to your help.
<img width="625" alt="FileNotFoundError" src="https://github.com/DongChen06/MARL_CAVs/assets/115389722/094d1e25-b856-4a1f-ba57-2c6034f6387b">

**Comment by DongChen06** [comment]
Hi, you may refer to the codes: https://drive.google.com/drive/folders/1CPOOYSQzqc0_XUr8durNWDUBv66PUHaM, which will generate the training logs
