### ISSUE TITLE
Regarding the running errors of run_madqn

### ISSUE THREAD

**Issue by danke93** [Derekabc/MARL_CAVs#41]
Thank you for your open-source materials. I have also tried to successfully run the run_mappo and run_maacktr models, but encountered an error while running the run_madqn model: **self. memory. push (state [agend_id,:], action [agend_id], reward [agend_id], next_state [agend_id,:]), done) TypeError: tuple indices must be integers or slices, not tuple**。 I tried debugging and it seems that there is **an issue with the index of state [agend_id,:]**.
I am using Gym=0.19.0 (using other versions may result in other errors and no model can run), but the photo you provided shows that you are using Gym=0.21.0. Is this an error caused by the Gym version? Looking forward to your reply.

**Comment by zcysun** [comment]
In the author's experience the DQN method does not apply to this method, you can try other methods

**Comment by DongChen06** [comment]
Hi, thanks for your interest. I am not sure its an issue with the versions. I was able to run the DQN approach but I was not able to achieve a good performance. There is one closed issue with all the libs I used, you may check that.
