### ISSUE TITLE
Algorithmic open source

### ISSUE THREAD

**Issue by zcysun** [Derekabc/MARL_CAVs#42]
Greetings!
First of all, congratulations on the inclusion of your article!
I read in #1 and #6 that you said you have plans to open source the algorithm after the article is included, and in #37 that you said the MASAC algorithm is not going to be open sourced for the time being, and I wanted to confirm with you that MASAC is the new approach you are proposing?
Thank you for your answer!

**Comment by DongChen06** [comment]
Hi, thanks for your interesting, the codes are already open-sourced. Please check the readme. MASAC is not the algorithm we proposed in the paper

**Comment by zcysun** [comment]
**Thank you for your response!**

I reviewed the README file and noticed that you have open-sourced four algorithms: MAA2C, MAPPO, MAACKTR, and MADQN. Additionally, I saw that in the Training Curves section of the README, MAA2C, MAPPO, and MAACKTR are the baseline algorithms you used for comparison. I recall that you mentioned in your paper that your proposed algorithm is an improved version based on A2C.

Therefore，I have three questions I hope you can help me with:

  1. Are your baseline algorithms the ones mentioned above (without parameter sharing, action masking, local reward design, and a priority-based safety supervisor), and is the "ours" algorithm the MAA2C with the new features added? (Referring to the MAA2C source code in the link: https://drive.google.com/drive/folders/1CPOOYSQzqc0_XUr8durNWDUBv66PUHaM, as mentioned in issue #27)
  
  2. Are the new features toggled in the following sections?
    - Safety supervisor: config.[ENV_CONFIG].safety_guarantee
    - Regional reward: config.[MODEL_CONFIG].reward_type
    - Action masking: config.[MODEL_CONFIG].action_masking
    - Parameter sharing: not found
  
  3. Where should parameter sharing be adjusted (if it can be adjusted)?

Thank you for your response, and best of luck with your research!

**Comment by DongChen06** [comment]
> **Thank you for your response!**
> 
> I reviewed the README file and noticed that you have open-sourced four algorithms: MAA2C, MAPPO, MAACKTR, and MADQN. Additionally, I saw that in the Training Curves section of the README, MAA2C, MAPPO, and MAACKTR are the baseline algorithms you used for comparison. I recall that you mentioned in your paper that your proposed algorithm is an improved version based on A2C.
> 
> Therefore，I have three questions I hope you can help me with:
> 
> 1. Are your baseline algorithms the ones mentioned above (without parameter sharing, action masking, local reward design, and a priority-based safety supervisor), and is the "ours" algorithm the MAA2C with the new features added? (Referring to the MAA2C source code in the link: https://drive.google.com/drive/folders/1CPOOYSQzqc0_XUr8durNWDUBv66PUHaM, as mentioned in issue [About the baseline in the paper #27](https://github.com/DongChen06/MARL_CAVs/issues/27))
> 2. Are the new features toggled in the following sections?
>    - Safety supervisor: config.[ENV_CONFIG].safety_guarantee
>    - Regional reward: config.[MODEL_CONFIG].reward_type
>    - Action masking: config.[MODEL_CONFIG].action_masking
>    - Parameter sharing: not found
> 3. Where should parameter sharing be adjusted (if it can be adjusted)?
> 
> Thank you for your response, and best of luck with your research!

1. Yes, the google drive link contains the main codes with all features.
2. Yes, all the features can be tuned in the configure file
3. If parameter sharing means the parameter sharing among agents, that is included in the network, you may find it in the model files. If you mean parameter sharing between actor and critic networks, you can set `shared_network = True'
Thanks

**Comment by zcysun** [comment]
Thanks for your reply！
