### ISSUE TITLE
About MAPPO with Safety Supervisor and Action Mask

### ISSUE THREAD

**Issue by gyccccccccc** [Derekabc/MARL_CAVs#46]
Hi! Thank you for your great job! Recently I want to add the action mask module(just change the actor network in model_common.py as the network in model.py ) and Safety Supervisor into MAPPO, but I find the performance of it is worse than MAPPO itself. I couldn't find out the reason. 
 So I really want to get your help, Could you tell me the safety supervisor can work in the mappo( I mean the performance of mappo with safety supervisor can be better than mappo) , or this module can only work in the maa2c?
(ps: the first image is the mappo with safety supervisor , the second is only mappo itself)

![图片1](https://github.com/DongChen06/MARL_CAVs/assets/142129312/2325f937-206e-40c9-8cd7-ba9ecf7d326d)

![图片2](https://github.com/DongChen06/MARL_CAVs/assets/142129312/19e79372-5392-42cf-9eb2-b6c83450d4b1)

**Comment by DongChen06** [comment]
Hi thanks for your interest. The safety supervisor can also be adapted to the MAPPO algorithm with few code changes. I am highly confident that it will improve the performance. The action masking may also improve the MAPPO. Intuitively, it works as well...

**Comment by gyccccccccc** [comment]
Thank you for your kindly reply, I just find that I've made some mistakes!
By the way, Could I ask another question? I wanna generate the vehicles trajectories in mappo.py, and use it in safety supervisor in abstract.py. Is that OK?

**Comment by gyccccccccc** [comment]
> Hi thanks for your interest. The safety supervisor can also be adapted to the MAPPO algorithm with few code changes. I am highly confident that it will improve the performance. The action masking may also improve the MAPPO. Intuitively, it works as well...

Wishing for your kind reply
