### ISSUE TITLE
Error when trying to run code

### ISSUE THREAD

**Issue by onkarrai06** [Derekabc/MARL_CAVs#47]
Greetings,

I hope you are doing well and I want to say props for the great work. I am writing to ask a question about the code which I can not seem to get running. Upon running the code in my conda environment, I got this error (when trying to run ma2c.py):

I inspected the code and found out that this is where the error is:

![image](https://github.com/DongChen06/MARL_CAVs/assets/121673391/de789773-1b55-4d87-8587-5243f7e6158d)

I believe the action_mask should be a numpy array and I don't understand why the error occurs. I have been debugging the code but to no avail. Can you let me know if this is an issue on my end because I have been trying to run it countlessly for hours.

These are the dependencies I got on my conda environment:

![image](https://github.com/DongChen06/MARL_CAVs/assets/121673391/d5968051-692b-4da7-99e6-6c2793fd102f)
![image](https://github.com/DongChen06/MARL_CAVs/assets/121673391/040aff76-8bda-4f52-9870-320023857417)

I would appreciate any insight, thank you.

**Comment by DongChen06** [comment]
Hi, thanks for your interest. You can find the issues and solutions in the closed issues

**Comment by onkarrai06** [comment]
> Hi, thanks for your interest. You can find the issues and solutions in the closed issues

I found this issue, however, this led to another error.
@DongChen06 

![image](https://github.com/DongChen06/MARL_CAVs/assets/121673391/708d3c51-1009-4386-981a-f22d98fea7a6)

**Comment by DongChen06** [comment]
Hi you can also find the solutions in the closed issues. Thanks

**Comment by onkarrai06** [comment]
> Hi you can also find the solutions in the closed issues. Thanks

Thanks for the prompt responses. I changed the utils.py code, but now when I try to run mappo.py it is stuck, is this what is supposed to happen or is there an issue?
@DongChen06 

![image](https://github.com/DongChen06/MARL_CAVs/assets/121673391/12153c07-fd76-4f69-a37a-57b373bcac25)

**Comment by onkarrai06** [comment]
Also, is there any way I can run this on my GPU instead? The training seems extremely slow on my CPU which is Ryzen 7 6800H.

@DongChen06
