### ISSUE TITLE
Approximate number of training episodes

### ISSUE THREAD

**Issue by redfish9** [Derekabc/MARL_CAVs#48]
Hi! @DongChen06 Thanks for your awesome work!

I'm trying to reproduce the results using MAA2C. The average reward remains rather fluctuating after 5,000 episodes, ranging from -5.82 at Episode 5,000 to 48.49 at Episode 5,200.
Could you please offer an approximate number of training sessions to achieve stationary?

This will certainly help me a lot.
Thanks again!

**Comment by DongChen06** [comment]
Hi, thanks for your interest. You can take a look at the paper to see if the training process is similar to it or not.

**Comment by 2901162744** [comment]
I have same question

**Comment by DongChen06** [comment]
usually, it takes more than 10k episodes to achieve stable rewards

**Comment by 2901162744** [comment]
I didn’t modify any parameters，and I would like to ask for your help.
![图片1](https://github.com/user-attachments/assets/833441f7-aef3-4863-8aff-70bef751ed14)
