### ISSUE TITLE
Safety Supervisor

### ISSUE THREAD

**Issue by archerZWC100** [Derekabc/MARL_CAVs#49]
where is Safety Supervisor ,I haven't seen Google Cloud Drive either

**Comment by DongChen06** [comment]
Hi, thanks for your interest. The safety supervisor can be found in the Abstract.py https://github.com/DongChen06/MARL_CAVs/blob/588f08d3dcd1505b1d0916063237318c29d24450/highway-env/highway_env/envs/common/abstract.py#L279

**Comment by archerZWC100** [comment]
Thank you very much
