### ISSUE TITLE
KeyError: 'MODEL_CONFIG'

### ISSUE THREAD

**Issue by tingtingLiuLiu** [Derekabc/MARL_CAVs#5]
Hello!  I need your help. When I run the run_mappo.py，and something went wrong. 
Looking forward to your reply, thanks .
![1629110114(1)](https://user-images.githubusercontent.com/45458399/129551365-76235079-e838-4e7b-a93a-32cd74e3ed57.png)

**Comment by DongChen06** [comment]
Hi, Can you go to the MARL folder and run `python run_mappo.py`? If it fails, could you please take a look at https://github.com/Derekabc/MARL_CAVs/issues/2 for how to run the code?
