### ISSUE TITLE
Building a road network environment

### ISSUE THREAD

**Issue by FlippedWayne** [Derekabc/MARL_CAVs#51]
Thank you for your work. I would like to know a possibility. 
May I ask if your code can run on this custom environment if I want to customize such a road network using "highway_env" library? Thank you for your answer！
![cfc327c4ec6785d7248d1fd9522097ab](https://github.com/user-attachments/assets/b22c1cd2-8131-42c9-b400-6a11a9b05ac1)

**Comment by DongChen06** [comment]
Hi @FlippedWayne, Thanks for your question. I think it is possible, but you may need to put in a lot of effort to build the network.

**Comment by FlippedWayne** [comment]
Thank you! I will try later.
