### ISSUE TITLE
Need a full version of requirements.txt

### ISSUE THREAD

**Issue by Nello416** [Derekabc/MARL_CAVs#55]
I try to run the file "run_ma2c.py", but I always fail on some problems for numpy array and I have to change the code to fix it. I think that's package version problem.
python 3.6 seems deprecated for the new version of gym, can u give the versions for every package in the requirements.txt plz:
numpy
pandas
gym
matplotlib
opencv-python
pygame

**Comment by DongChen06** [comment]
https://github.com/DongChen06/MARL_CAVs/issues/18

**Comment by Nello416** [comment]
thank you
