### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: merge-multi-agent-v0

### ISSUE THREAD

**Issue by KumudaBG** [Derekabc/MARL_CAVs#8]
Hi @Derekabc ,

I have followed the steps mentioned in git repo, also made the MARL and highway-env as directory root. But still have the below error while running the program in PyCharm 2018.3.5 (Community Edition)

<img width="918" alt="Screen Shot 2021-10-31 at 9 51 41 PM" src="https://user-images.githubusercontent.com/71955355/139623981-c5279b83-f13c-4195-88e3-ac7243c8082b.png">

Could you please help.

Thanks in advance

**Comment by DongChen06** [comment]
Hi, Kumuda, thanks for your interest. Could you please check whether this file exists?
![image](https://user-images.githubusercontent.com/25771207/139677456-c7715368-448a-42bc-8bee-e9dff2c9ce7c.png)
Or you can add the following code in the run_mappo.py. 
```
import sys
sys.path.append("../highway-env")
```

**Comment by KumudaBG** [comment]
Thank you for your reply @Derekabc . Please note, this error occurs when I try to run he run_mappo.py from terminal.  And both of your suggestions are implemented but still the error appears. 

Also when I execute the run_mappo.py using run options (highlighted in white marker) :
<img width="1394" alt="Screen Shot 2021-11-01 at 4 42 50 PM" src="https://user-images.githubusercontent.com/71955355/139756925-4bb7a09d-8416-4811-a223-bf73ff55f437.png">

I get the error: "/Users/suhas/venv/bin/python: can't find '__main__' module in '/Users/suhas/opt/anaconda3/envs/marl_cav/lib/python3.6'"

You can see the error too in the screenshot provided.

**Comment by DongChen06** [comment]
@KumudaBG Could you reach me out via email and we can have a quick chat to find the issues if you want

**Comment by qiangyuchuan** [comment]
Hi @Derekabc ,

![报错](https://user-images.githubusercontent.com/82998341/140026909-5a5574c1-db72-4665-924d-e83a0d759a6f.png)
I have almost the same problem. I have the below error while running the program in a server within a virtualenv created by conda,the version of python is 3.7.
I wonder if I got the right version of gym?

**Comment by DongChen06** [comment]
@KumudaBG @qiangyuchuan  I just tested the code on a new Ubuntu20.04 machine, it seems it can run successfully without any issues. I made some small changes to the code, thus we do not need to make any directories as the source directory. The main steps are:

1. download the code.
2. create the environment and install the libs
3. click run_xx.py

The issues may come from the different platforms. Following is the libs I have:
![image](https://user-images.githubusercontent.com/25771207/140172753-87b4567d-b5c3-4e49-b0c4-84ef2786b767.png)

**Comment by KumudaBG** [comment]
Hi Dong,

Thanks for letting me know the response in Ubuntu. I was able to fix the
unregisteredEnv error after placing the below lines of code on top of the
run_mappo.py file.

import sys
sys.path.append("/Users/suhas/Desktop/SJSU/SEM4/CMPE260/MARL_CAVs/highway-env")


But getting this error.
[image: Screen Shot 2021-11-03 at 11.51.37 AM.png]
Because I don't have any models in the results/models folder.

Could you please help me with this?

Regards,
Kumuda

**Comment by DongChen06** [comment]
@KumudaBG  It seems the image is broken and I cannot see it.

**Comment by kumudamurthy** [comment]
> @KumudaBG It seems the image is broken and I cannot see it.

![image](https://user-images.githubusercontent.com/89551885/140175307-7cc84146-af1c-4471-8af1-2874504b21b6.png)

Here is the error @Derekabc

**Comment by DongChen06** [comment]
@KumudaBG  actually, it's not an error and just tells you that there is no pretrained model to load. You will see the evaluation videos soon.

**Comment by kumudamurthy** [comment]
@Derekabc will wait for it and let you know, thank you. 
After the evaluation, will there be a model saved in that folder?

**Comment by DongChen06** [comment]
> @Derekabc will wait for it and let you know, thank you. After the evaluation, will there be a model saved in that folder?

yes, there should be videos and models saved in the folder.

**Comment by KumudaBG** [comment]
Hi Dong,

I was able to run the run_mappo.py successfully. thank you
